/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.example.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

/** This is a Avro schema for IEX Trading API */
@org.apache.avro.specific.AvroGenerated
public class IexTrading extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -319107827241929004L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"IexTrading\",\"namespace\":\"com.example.avro\",\"doc\":\"This is a Avro schema for IEX Trading API\",\"fields\":[{\"name\":\"symbol\",\"type\":\"string\"},{\"name\":\"companyName\",\"type\":[\"null\",\"string\"],\"doc\":\"Company Name\",\"avro.java.string\":\"String\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<IexTrading> ENCODER =
      new BinaryMessageEncoder<IexTrading>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<IexTrading> DECODER =
      new BinaryMessageDecoder<IexTrading>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<IexTrading> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<IexTrading> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<IexTrading> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<IexTrading>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this IexTrading to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a IexTrading from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a IexTrading instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static IexTrading fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence symbol;
  /** Company Name */
  @Deprecated public java.lang.CharSequence companyName;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public IexTrading() {}

  /**
   * All-args constructor.
   * @param symbol The new value for symbol
   * @param companyName Company Name
   */
  public IexTrading(java.lang.CharSequence symbol, java.lang.CharSequence companyName) {
    this.symbol = symbol;
    this.companyName = companyName;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return symbol;
    case 1: return companyName;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: symbol = (java.lang.CharSequence)value$; break;
    case 1: companyName = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'symbol' field.
   * @return The value of the 'symbol' field.
   */
  public java.lang.CharSequence getSymbol() {
    return symbol;
  }


  /**
   * Sets the value of the 'symbol' field.
   * @param value the value to set.
   */
  public void setSymbol(java.lang.CharSequence value) {
    this.symbol = value;
  }

  /**
   * Gets the value of the 'companyName' field.
   * @return Company Name
   */
  public java.lang.CharSequence getCompanyName() {
    return companyName;
  }


  /**
   * Sets the value of the 'companyName' field.
   * Company Name
   * @param value the value to set.
   */
  public void setCompanyName(java.lang.CharSequence value) {
    this.companyName = value;
  }

  /**
   * Creates a new IexTrading RecordBuilder.
   * @return A new IexTrading RecordBuilder
   */
  public static com.example.avro.IexTrading.Builder newBuilder() {
    return new com.example.avro.IexTrading.Builder();
  }

  /**
   * Creates a new IexTrading RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new IexTrading RecordBuilder
   */
  public static com.example.avro.IexTrading.Builder newBuilder(com.example.avro.IexTrading.Builder other) {
    if (other == null) {
      return new com.example.avro.IexTrading.Builder();
    } else {
      return new com.example.avro.IexTrading.Builder(other);
    }
  }

  /**
   * Creates a new IexTrading RecordBuilder by copying an existing IexTrading instance.
   * @param other The existing instance to copy.
   * @return A new IexTrading RecordBuilder
   */
  public static com.example.avro.IexTrading.Builder newBuilder(com.example.avro.IexTrading other) {
    if (other == null) {
      return new com.example.avro.IexTrading.Builder();
    } else {
      return new com.example.avro.IexTrading.Builder(other);
    }
  }

  /**
   * RecordBuilder for IexTrading instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<IexTrading>
    implements org.apache.avro.data.RecordBuilder<IexTrading> {

    private java.lang.CharSequence symbol;
    /** Company Name */
    private java.lang.CharSequence companyName;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.example.avro.IexTrading.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.symbol)) {
        this.symbol = data().deepCopy(fields()[0].schema(), other.symbol);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.companyName)) {
        this.companyName = data().deepCopy(fields()[1].schema(), other.companyName);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing IexTrading instance
     * @param other The existing instance to copy.
     */
    private Builder(com.example.avro.IexTrading other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.symbol)) {
        this.symbol = data().deepCopy(fields()[0].schema(), other.symbol);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.companyName)) {
        this.companyName = data().deepCopy(fields()[1].schema(), other.companyName);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'symbol' field.
      * @return The value.
      */
    public java.lang.CharSequence getSymbol() {
      return symbol;
    }


    /**
      * Sets the value of the 'symbol' field.
      * @param value The value of 'symbol'.
      * @return This builder.
      */
    public com.example.avro.IexTrading.Builder setSymbol(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.symbol = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'symbol' field has been set.
      * @return True if the 'symbol' field has been set, false otherwise.
      */
    public boolean hasSymbol() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'symbol' field.
      * @return This builder.
      */
    public com.example.avro.IexTrading.Builder clearSymbol() {
      symbol = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'companyName' field.
      * Company Name
      * @return The value.
      */
    public java.lang.CharSequence getCompanyName() {
      return companyName;
    }


    /**
      * Sets the value of the 'companyName' field.
      * Company Name
      * @param value The value of 'companyName'.
      * @return This builder.
      */
    public com.example.avro.IexTrading.Builder setCompanyName(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.companyName = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'companyName' field has been set.
      * Company Name
      * @return True if the 'companyName' field has been set, false otherwise.
      */
    public boolean hasCompanyName() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'companyName' field.
      * Company Name
      * @return This builder.
      */
    public com.example.avro.IexTrading.Builder clearCompanyName() {
      companyName = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public IexTrading build() {
      try {
        IexTrading record = new IexTrading();
        record.symbol = fieldSetFlags()[0] ? this.symbol : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.companyName = fieldSetFlags()[1] ? this.companyName : (java.lang.CharSequence) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<IexTrading>
    WRITER$ = (org.apache.avro.io.DatumWriter<IexTrading>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<IexTrading>
    READER$ = (org.apache.avro.io.DatumReader<IexTrading>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.symbol);

    if (this.companyName == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.companyName);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.symbol = in.readString(this.symbol instanceof Utf8 ? (Utf8)this.symbol : null);

      if (in.readIndex() != 1) {
        in.readNull();
        this.companyName = null;
      } else {
        this.companyName = in.readString(this.companyName instanceof Utf8 ? (Utf8)this.companyName : null);
      }

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.symbol = in.readString(this.symbol instanceof Utf8 ? (Utf8)this.symbol : null);
          break;

        case 1:
          if (in.readIndex() != 1) {
            in.readNull();
            this.companyName = null;
          } else {
            this.companyName = in.readString(this.companyName instanceof Utf8 ? (Utf8)this.companyName : null);
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










